name: Tests

on:
  pull_request:
  push:
    branches: main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Poetry, tox and dev dependencies
        run: |
          curl -sSL https://install.python-poetry.org | python - -y
          pip install tox
          poetry install --only dev
      - name: Run tests
        run: |
          poetry run tox
